version: '3'

services:
  postgres:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres12345
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432